services:
  
  postgres:
    image: postgres
    container_name: postgresdb
    environment: 
      POSTGRES_USER: wesleydb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
  

